[package]
name = "expressive"
version = "0.0.1"
edition = "2021"

[workspace]
members = [
    "expressive-expression",
    "expressive-runtime"
]

[[bin]]
name = "exressive_runtime"
path = "expressive-runtime/src/main.rs"
