[package]
name = "expressive"
version = "0.0.1"
edition = "2021"

[workspace]
members = [
    "expressive_data",
    "expressive_domain",
    "expressive_expression",
    "expressive_runtime"
]

[[bin]]
name = "expressive_runtime"
path = "expressive_runtime/src/main.rs"
