[package]
name = "expressive_expression"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = "0.4.7"
pest = "2.7.15"
pest_derive = "2.7.15"
thiserror = "2.0.11"
expressive_data = { path = "../expressive_data" }